In [1]:
import numpy as np
import pandas as pd

from stanbkt.models.standard import StandardBKT

/home/sppradhan/Desktop/Research/StanBKT/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def sim_simple_BKT(
    rng=np.random.default_rng(0),
    nStudents: int = 10,
    nProblems: int = 20,
    nKcs: int = 1,
    prior=0.1,
    learn=0.01,
    forget=0.05,
    guess=0.2,
    slip=0.1,
    kc_sequence=None,
):

    def _param_to_vec(x, name):
        arr = np.asarray(x, dtype=float)
        if arr.size == 1:
            arr = np.repeat(arr, nKcs)
        if arr.size != nKcs:
            raise ValueError(f"{name} must be scalar or length nKcs")
        return arr

    prior_vec = _param_to_vec(prior, "prior")
    learn_vec = _param_to_vec(learn, "learn")
    forget_vec = _param_to_vec(forget, "forget")
    guess_vec = _param_to_vec(guess, "guess")
    slip_vec = _param_to_vec(slip, "slip")

    if kc_sequence is None:
        kc_sequence = rng.integers(0, nKcs, size=nProblems)
    else:
        kc_sequence = np.asarray(kc_sequence, dtype=int)
        if kc_sequence.shape[0] != nProblems:
            raise ValueError("kc_sequence must have length nProblems")
        if kc_sequence.min() < 0 or kc_sequence.max() >= nKcs:
            raise ValueError("kc_sequence entries must be in [0, nKcs-1]")

    knowledge = rng.random(size=(nStudents, nKcs)) < prior_vec
    correctness = np.zeros((nStudents, nProblems), dtype=int)
    states = np.zeros((nStudents, nProblems), dtype=int)

    for t in range(nProblems):
        kc = kc_sequence[t]
        for s in range(nStudents):
            knows_before = knowledge[s, kc]
            if knows_before:
                correct = int(rng.random() >= slip_vec[kc])
            else:
                correct = int(rng.random() < guess_vec[kc])

            correctness[s, t] = correct

            if knows_before:
                knowledge[s, kc] = rng.random() >= forget_vec[kc]
            else:
                knowledge[s, kc] = rng.random() < learn_vec[kc]

            states[s, t] = knowledge[s, kc]

    return (
        correctness,
        states,
        kc_sequence,
        nStudents,
        nProblems,
        nKcs,
    )

In [3]:
# 1) Generate synthetic data (from scratch.ipynb logic)
(
    correctness,
    states,
    kc_sequence,
    n_students,
    n_problems,
    n_kcs,
 ) = sim_simple_BKT(
    rng=np.random.default_rng(123),
    nStudents=50,
    nProblems=30,
    nKcs=3,
    prior=0.4,
    learn=0.04,
    forget=0.01,
    guess=0.2,
    slip=0.1,
    kc_sequence=None,
)

correctness.shape, n_kcs

((50, 30), 3)

In [4]:
# 2) Build long-format dataframe expected by StanBKT
student_idx, problem_idx = np.indices(correctness.shape)

data_df = pd.DataFrame(
    {
        "student_id": student_idx.ravel().astype(str),
        "problem_id": problem_idx.ravel().astype(str),
        "correct": correctness.ravel().astype(int),
        "kc_id": kc_sequence[problem_idx.ravel()].astype(str),
    }
)

data_df

     student_id problem_id  correct kc_id
0             0          0        0     0
1             0          1        0     2
2             0          2        1     1
3             0          3        0     0
4             0          4        1     2
...         ...        ...      ...   ...
1495         49         25        1     2
1496         49         26        1     2
1497         49         27        1     0
1498         49         28        1     1
1499         49         29        1     2

[1500 rows x 4 columns]

In [5]:
data_df['kc_id'].value_counts()

kc_id
0    600
2    550
1    350
Name: count, dtype: int64

In [6]:
# 3) Instantiate and fit the StandardBKT model
model = StandardBKT()
model.fit(data_df)

13:41:45 - cmdstanpy - INFO - CmdStan start processing
chain 1:   0%|          | 0/3500 [00:00<?, ?it/s, (Warmup)]






chain 1:   3%|▎         | 100/3500 [00:00<00:10, 319.89it/s, (Warmup)]





chain 1:   6%|▌         | 200/3500 [00:00<00:09, 358.66it/s, (Warmup)]


chain 1:   9%|▊         | 300/3500 [00:00<00:06, 461.27it/s, (Warmup)]


chain 1:  11%|█▏        | 400/3500 [00:00<00:05, 520.65it/s, (Warmup)]


chain 1:  14%|█▍        | 500/3500 [00:01<00:05, 555.41it/s, (Warmup)]


chain 1:  17%|█▋        | 600/3500 [00:01<00:05, 578.99it/s, (Warmup)]

chain 1:  20%|██        | 700/3500 [00:01<00:04, 615.99it/s, (Warmup)]


chain 1:  23%|██▎       | 800/3500 [00:01<00:04, 626.42it/s, (Warmup)]


chain 1:  26%|██▌       | 900/3500 [00:01<00:04, 621.77it/s, (Warmup)]


chain 1:  29%|██▊       | 1000/3500 [00:01<00:04, 618.66it/s, (Warmup)]


chain 1:  31%|███▏      | 1100/3500 [00:01<00:03, 641.98it/s, (Warmup)]


chain 1:  34%|███▍      | 1200/3500 [00:02<00:03, 698.39it/s, (Warmup)]


chain 1:  37%|███▋      | 1300/3500 [00:02<00:03, 706.77it/s, (Warmup)]

chain 1:  40%|████      | 1400/3500 [00:02<00:02, 743.37it/s, (Warmup)]


chain 1:  43%|████▎     | 1500/3500 [00:02<00:02, 766.01it/s, (Warmup)]


chain 1:  49%|████▊     | 1700/3500 [00:02<00:02, 871.45it/s, (Warmup)]


chain 1:  54%|█████▍    | 1900/3500 [00:02<00:01, 833.30it/s, (Warmup)]






chain 1:  57%|█████▋    | 2000/3500 [00:03<00:02, 745.96it/s, (Sampling)]


chain 1:  60%|██████    | 2100/3500 [00:03<00:01, 719.14it/s, (Sampling)]


chain 1:  63%|██████▎   | 2200/3500 [00:03<00:01, 707.37it/s, (Sampling)]
chain 1:  66%|██████▌   | 2300/3500 [00:03<00:01, 699.36it/s, (Sampling)]


chain 1:  69%|██████▊   | 2400/3500 [00:03<00:01, 681.57it/s, (Sampling)]


chain 1:  71%|███████▏  | 2500/3500 [00:03<00:01, 683.24it/s, (Sampling)]
chain 1:  74%|███████▍  | 2600/3500 [00:03<00:01, 670.68it/s, (Sampling)]



chain 1:  77%|███████▋  | 2700/3500 [00:04<00:01, 671.17it/s, (Sampling)]

chain 1:  80%|████████  | 2800/3500 [00:04<00:01, 661.19it/s, (Sampling)]


chain 1:  83%|████████▎ | 2900/3500 [00:04<00:00, 657.05it/s, (Sampling)]
chain 1:  86%|████████▌ | 3000/3500 [00:04<00:00, 654.26it/s, (Sampling)]



chain 1:  89%|████████▊ | 3100/3500 [00:04<00:00, 649.91it/s, (Sampling)]

chain 1:  94%|█████████▍| 3300/3500 [00:05<00:00, 655.21it/s, (Sampling)]

chain 1:  97%|█████████▋| 3400/3500 [00:05<00:00, 657.06it/s, (Sampling)]

chain 1: 100%|██████████| 3500/3500 [00:05<00:00, 696.36it/s, (Sampling)]







chain 1: 100%|██████████| 3500/3500 [00:05<00:00, 597.86it/s, (Sampling completed)]
chain 2: 100%|██████████| 3500/3500 [00:05<00:00, 597.73it/s, (Sampling completed)]

chain 3: 100%|██████████| 3500/3500 [00:05<00:00, 597.70it/s, (Sampling completed)]


chain 4: 100%|██████████| 3500/3500 [00:05<00:00, 597.61it/s, (Sampling completed)]

13:41:51 - cmdstanpy - INFO - CmdStan done processing.
13:41:51 - cmdstanpy - INFO - CmdStan start processing

chain 1:   0%|          | 0/3500 [00:00<?, ?it/s, (Warmup)]



chain 1:   3%|▎         | 100/3500 [00:00<00:09, 374.38it/s, (Warmup)]




chain 1:   6%|▌         | 200/3500 [00:00<00:07, 441.47it/s, (Warmup)]


chain 1:   9%|▊         | 300/3500 [00:00<00:06, 475.27it/s, (Warmup)]


chain 1:  11%|█▏        | 400/3500 [00:00<00:06, 514.99it/s, (Warmup)]




chain 1:  14%|█▍        | 500/3500 [00:01<00:05, 527.14it/s, (Warmup)]



chain 1:  17%|█▋        | 600/3500 [00:01<00:05, 528.80it/s, (Warmup)]


chain 1:  20%|██        | 700/3500 [00:01<00:05, 503.30it/s, (Warmup)]


chain 1:  23%|██▎       | 800/3500 [00:01<00:05, 521.08it/s, (Warmup)]


chain 1:  26%|██▌       | 900/3500 [00:01<00:04, 529.17it/s, (Warmup)]


chain 1:  29%|██▊       | 1000/3500 [00:01<00:04, 573.48it/s, (Warmup)]




chain 1:  31%|███▏      | 1100/3500 [00:02<00:04, 587.49it/s, (Warmup)]


chain 1:  34%|███▍      | 1200/3500 [00:02<00:03, 607.98it/s, (Warmup)]




chain 1:  37%|███▋      | 1300/3500 [00:02<00:03, 634.45it/s, (Warmup)]
chain 1:  40%|████      | 1400/3500 [00:02<00:03, 636.61it/s, (Warmup)]



chain 1:  43%|████▎     | 1500/3500 [00:02<00:03, 664.93it/s, (Warmup)]


chain 1:  46%|████▌     | 1600/3500 [00:02<00:02, 682.34it/s, (Warmup)]



chain 1:  49%|████▊     | 1700/3500 [00:02<00:02, 681.75it/s, (Warmup)]


chain 1:  51%|█████▏    | 1800/3500 [00:03<00:02, 684.26it/s, (Warmup)]

chain 1:  54%|█████▍    | 1900/3500 [00:03<00:02, 687.28it/s, (Warmup)]

chain 1:  57%|█████▋    | 2000/3500 [00:03<00:02, 650.63it/s, (Sampling)]


chain 1:  60%|██████    | 2100/3500 [00:03<00:02, 688.27it/s, (Sampling)]



chain 1:  63%|██████▎   | 2200/3500 [00:03<00:01, 719.87it/s, (Sampling)]


chain 1:  66%|██████▌   | 2300/3500 [00:03<00:01, 734.55it/s, (Sampling)]


chain 1:  69%|██████▊   | 2400/3500 [00:03<00:01, 742.76it/s, (Sampling)]


chain 1:  71%|███████▏  | 2500/3500 [00:04<00:01, 754.70it/s, (Sampling)]


chain 1:  74%|███████▍  | 2600/3500 [00:04<00:01, 768.17it/s, (Sampling)]


chain 1:  77%|███████▋  | 2700/3500 [00:04<00:01, 771.21it/s, (Sampling)]

chain 1:  80%|████████  | 2800/3500 [00:04<00:00, 782.56it/s, (Sampling)]




chain 1:  86%|████████▌ | 3000/3500 [00:04<00:00, 935.60it/s, (Sampling)]


chain 1: 100%|██████████| 3500/3500 [00:05<00:00, 699.93it/s, (Sampling completed)]
chain 2: 100%|██████████| 3500/3500 [00:04<00:00, 700.08it/s, (Sampling completed)]

chain 3: 100%|██████████| 3500/3500 [00:04<00:00, 700.59it/s, (Sampling completed)]


chain 4: 100%|██████████| 3500/3500 [00:04<00:00, 700.83it/s, (Sampling completed)]

13:41:56 - cmdstanpy - INFO - CmdStan done processing.
13:41:56 - cmdstanpy - INFO - CmdStan start processing

chain 1:   0%|          | 0/3500 [00:00<?, ?it/s, (Warmup)]





chain 1:   3%|▎         | 100/3500 [00:00<00:06, 495.29it/s, (Warmup)]


chain 1:   6%|▌         | 200/3500 [00:00<00:05, 624.37it/s, (Warmup)]

chain 1:   9%|▊         | 300/3500 [00:00<00:04, 701.02it/s, (Warmup)]


chain 1:  11%|█▏        | 400/3500 [00:00<00:04, 709.60it/s, (Warmup)]


chain 1:  14%|█▍        | 500/3500 [00:00<00:04, 699.98it/s, (Warmup)]


chain 1:  17%|█▋        | 600/3500 [00:00<00:03, 736.26it/s, (Warmup)]


chain 1:  20%|██        | 700/3500 [00:00<00:03, 734.65it/s, (Warmup)]


chain 1:  23%|██▎       | 800/3500 [00:01<00:03, 757.79it/s, (Warmup)]




chain 1:  26%|██▌       | 900/3500 [00:01<00:03, 688.87it/s, (Warmup)]
chain 1:  29%|██▊       | 1000/3500 [00:01<00:03, 712.05it/s, (Warmup)]


chain 1:  31%|███▏      | 1100/3500 [00:01<00:03, 727.05it/s, (Warmup)]


chain 1:  34%|███▍      | 1200/3500 [00:01<00:03, 725.63it/s, (Warmup)]
chain 1:  37%|███▋      | 1300/3500 [00:01<00:03, 731.80it/s, (Warmup)]



chain 1:  40%|████      | 1400/3500 [00:01<00:02, 752.35it/s, (Warmup)]


chain 1:  43%|████▎     | 1500/3500 [00:02<00:02, 734.82it/s, (Warmup)]
chain 1:  46%|████▌     | 1600/3500 [00:02<00:02, 741.59it/s, (Warmup)]




chain 1:  49%|████▊     | 1700/3500 [00:02<00:02, 751.79it/s, (Warmup)]
chain 1:  51%|█████▏    | 1800/3500 [00:02<00:02, 750.78it/s, (Warmup)]


chain 1:  54%|█████▍    | 1900/3500 [00:02<00:02, 745.57it/s, (Warmup)]

chain 1:  57%|█████▋    | 2000/3500 [00:02<00:02, 734.41it/s, (Sampling)]


chain 1:  60%|██████    | 2100/3500 [00:02<00:01, 743.13it/s, (Sampling)]


chain 1:  66%|██████▌   | 2300/3500 [00:03<00:01, 781.33it/s, (Sampling)]


chain 1:  69%|██████▊   | 2400/3500 [00:03<00:01, 809.08it/s, (Sampling)]
chain 1:  71%|███████▏  | 2500/3500 [00:03<00:01, 793.47it/s, (Sampling)]


chain 1:  74%|███████▍  | 2600/3500 [00:03<00:01, 780.27it/s, (Sampling)]


chain 1:  77%|███████▋  | 2700/3500 [00:03<00:00, 818.32it/s, (Sampling)]


chain 1:  83%|████████▎ | 2900/3500 [00:03<00:00, 893.51it/s, (Sampling)]


chain 1:  86%|████████▌ | 3000/3500 [00:03<00:00, 906.78it/s, (Sampling)]
chain 1:  89%|████████▊ | 3100/3500 [00:04<00:00, 909.25it/s, (Sampling)]

chain 1:  91%|█████████▏| 3200/3500 [00:04<00:00, 913.54it/s, (Sampling)]
chain 1:  94%|█████████▍| 3300/3500 [00:04<00:00, 932.47it/s, (Sampling)]


chain 1:  97%|█████████▋| 3400/3500 [00:04<00:00, 948.52it/s, (Sampling)]











chain 1: 100%|██████████| 3500/3500 [00:04<00:00, 713.11it/s, (Sampling completed)]
chain 2: 100%|██████████| 3500/3500 [00:04<00:00, 713.11it/s, (Sampling completed)]

chain 3: 100%|██████████| 3500/3500 [00:04<00:00, 713.19it/s, (Sampling completed)]


chain 4: 100%|██████████| 3500/3500 [00:04<00:00, 713.23it/s, (Sampling completed)]

13:42:01 - cmdstanpy - INFO - CmdStan done processing.

In [7]:
model

In [10]:
model.fits_['0'].save_csvfiles("./test/here")

In [11]:
import cmdstanpy

In [12]:
import cmdstanpy
fit_test = cmdstanpy.from_csv("./test/here/")

In [18]:
fit_test.metadata

Metadata:
{'stan_version_major': 2, 'stan_version_minor': 36, 'stan_version_patch': 0, 'model': 'BKT_model_model', 'start_datetime': '2026-03-05 18:41:45 UTC', 'method': 'sample', 'num_samples': 1500, 'num_warmup': 2000, 'save_warmup': 0, 'thin': 2, 'engaged': 1, 'gamma': 0.05, 'delta': 0.8, 'kappa': 0.75, 't0': 10, 'init_buffer': 75, 'term_buffer': 50, 'window': 25, 'save_metric': 0, 'algorithm': 'hmc', 'engine': 'nuts', 'max_depth': 10, 'metric': 'diag_e', 'metric_file': '', 'stepsize': 1, 'stepsize_jitter': 0, 'num_chains': 1, 'id': 1, 'data_file': '/tmp/tmpmiyx7_1i/s9v2_tp0.json', 'init': 2, 'seed': 1, 'diagnostic_file': '', 'refresh': 100, 'sig_figs': -1, 'profile_file': 'profile.csv', 'save_cmdstan_config': 0, 'num_threads': 1, 'stanc_version': 'stanc3 v2.36.0', 'stancflags': '--filename-in-msg=BKT_model.stan', 'Step size': 0.415398, 'raw_header': 'lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,divergent__,energy__,logit_pi_know_group.1,logit_learn_group.1,logit_forget_group.1,logit_guess_group.1,logit_slip_group.1,pi_know.1,learn.1,forget.1,guess.1,slip.1', 'column_names': ('lp__', 'accept_stat__', 'stepsize__', 'treedepth__', 'n_leapfrog__', 'divergent__', 'energy__', 'logit_pi_know_group[1]', 'logit_learn_group[1]', 'logit_forget_group[1]', 'logit_guess_group[1]', 'logit_slip_group[1]', 'pi_know[1]', 'learn[1]', 'forget[1]', 'guess[1]', 'slip[1]'), 'draws_warmup': 0, 'draws_sampling': 750, 'ct_divergences': np.int64(0), 'ct_max_treedepth': np.int64(0), 'time': {'warmup': 3.049, 'sampling': 2.253, 'total': 5.302}}

In [26]:
for file in model.fits_.get('0').runset.csv_files:
    print(open(file).read())

# stan_version_major = 2
# stan_version_minor = 36
# stan_version_patch = 0
# model = BKT_model_model
# start_datetime = 2026-03-04 23:36:24 UTC
# method = sample (Default)
#   sample
#     num_samples = 1500
#     num_warmup = 2000
#     save_warmup = false (Default)
#     thin = 2
#     adapt
#       engaged = true (Default)
#       gamma = 0.05 (Default)
#       delta = 0.8 (Default)
#       kappa = 0.75 (Default)
#       t0 = 10 (Default)
#       init_buffer = 75 (Default)
#       term_buffer = 50 (Default)
#       window = 25 (Default)
#       save_metric = false (Default)
#     algorithm = hmc (Default)
#       hmc
#         engine = nuts (Default)
#           nuts
#             max_depth = 10 (Default)
#         metric = diag_e (Default)
#         metric_file =  (Default)
#         stepsize = 1 (Default)
#         stepsize_jitter = 0 (Default)
#     num_chains = 1 (Default)
# id = 1 (Default)
# data
#   file = /tmp/tmper9i5bc4/f3d_gv8n.json
# init = 2 (Default)
# random
#   seed = 1
# output
#   file = /tmp/tmper9i5bc4/BKT_modelusfdp95o/BKT_model-20260304183624_1.csv
#   diagnostic_file =  (Default)
#   refresh = 100 (Default)
#   sig_figs = -1 (Default)
#   profile_file = profile.csv (Default)
#   save_cmdstan_config = false (Default)
# num_threads = 1 (Default)
# stanc_version = stanc3 v2.36.0
# stancflags = --filename-in-msg=BKT_model.stan
lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,divergent__,energy__,logit_pi_know_group.1,logit_learn_group.1,logit_forget_group.1,logit_guess_group.1,logit_slip_group.1,pi_know.1,learn.1,forget.1,guess.1,slip.1
# Adaptation terminated
# Step size = 0.415398
# Diagonal elements of inverse mass matrix:
# 0.10282, 5.80677, 0.279729, 0.0522956, 0.085029
-307.61,0.334991,0.415398,2,3,0,311.289,-0.247389,-4.53034,-3.22087,-0.368826,-1.49077,0.438466,0.0106621,0.0383879,0.204412,0.091903
-310.421,0.884376,0.415398,3,7,0,312.512,0.467199,-12.7907,-2.98684,-0.955042,-1.17594,0.614721,2.78659e-06,0.048024,0.138936,0.117892
-310.233,0.706374,0.415398,3,7,0,311.893,-0.134351,-10.0777,-4.75403,-0.240734,-1.19657,0.466463,4.20042e-05,0.00854326,0.220053,0.116043
-308.926,0.818392,0.415398,3,11,0,311.327,0.237948,-11.81,-4.12837,-0.5606,-1.20252,0.559208,7.42962e-06,0.0158538,0.181704,0.115513
-308.013,0.974821,0.415398,3,7,0,309.355,0.130167,-3.71906,-3.37943,-0.592824,-1.52212,0.532496,0.0236824,0.0329447,0.177994,0.0895747
-307.91,0.998261,0.415398,3,7,0,308.76,0.0791217,-9.48974,-4.25753,-0.543649,-0.915009,0.51977,7.5618e-05,0.0139595,0.18367,0.142988
-306.871,0.991462,0.415398,3,7,0,308.107,0.207631,-5.86969,-3.04596,-0.757629,-0.907011,0.551722,0.0028158,0.0453923,0.159581,0.143806
-307.019,0.454494,0.415398,3,7,0,309.572,0.0929086,-9.35694,-3.76921,-0.581013,-1.16499,0.52321,8.63564e-05,0.02255,0.17935,0.118881
-307.319,0.956883,0.415398,3,7,0,308.202,0.561456,-6.35414,-3.7751,-0.708894,-1.15008,0.636789,0.00173652,0.0224205,0.164922,0.120237
-308.727,0.935167,0.415398,3,7,0,312.39,0.0100161,-5.64598,-4.85766,-0.751954,-0.86902,0.502504,0.00351925,0.00770876,0.160198,0.147729
-309.445,0.69533,0.415398,3,11,0,314.496,-0.179771,-5.98934,-2.75918,-0.95272,-1.2146,0.455178,0.00249906,0.0595701,0.139169,0.114444
-308.382,0.99579,0.415398,3,7,0,309.792,0.434883,-4.65294,-4.18137,-0.758888,-1.09639,0.607039,0.00944351,0.0150477,0.159444,0.125208
-311.392,0.96546,0.415398,3,7,0,313.509,0.48737,-5.08359,-4.48643,-0.176273,-1.18245,0.619487,0.00615947,0.0111354,0.228023,0.117306
-308.06,0.969385,0.415398,3,7,0,308.598,0.0228541,-4.56349,-4.10426,-0.78533,-1.3268,0.505713,0.010318,0.0162343,0.156586,0.104844
-312.259,0.947327,0.415398,3,7,0,314.681,0.746098,-4.43564,-4.05534,-0.859494,-1.5085,0.678328,0.0117088,0.0170344,0.148723,0.0905803
-309.814,0.999839,0.415398,3,7,0,311.858,0.725646,-7.61714,-4.13838,-0.947722,-1.01299,0.673849,0.000491704,0.0156984,0.139672,0.133198
-306.859,0.997837,0.415398,3,7,0,308.507,-0.0113464,-8.08717,-3.81286,-0.781275,-1.04784,0.497163,0.000307365,0.0216077,0.157023,0.12982
-306.479,0.985268,0.415398,3,7,0,308.313,0.422787,-6.17003,-3.48238,-0.567948,-1.12278,0.60415,0.00208681,0.0298176,0.180855,0.122748
-308.63,0.976979,0.415398,3,7,0,309.545,0.209328,-6.15855,-3.58549,-0.173322,-1.39702,0.552142,0.00211085,0.0269753,0.228389,0.0991449
-306.936,0.97401,0.415398,3,7,0,310.435,0.369701,-7.21866,-3.69852,-0.463061,-1.06393,0.591387,0.000732247,0.0241619,0.19313,0.12828
-308.159,0.890711,0.415398,3,15,0,309.913,0.19739,-8.08094,-3.08021,-0.537079,-1.5355,0.549188,0.000309286,0.0439309,0.184434,0.0885952
-307.63,0.981912,0.415398,3,7,0,309.41,-0.387704,-6.21483,-3.37508,-0.458579,-1.11635,0.40427,0.00199557,0.0330833,0.193661,0.123344
-309.452,0.975227,0.415398,3,7,0,309.964,-0.200605,-8.68475,-4.51621,-0.892226,-0.902264,0.450016,0.000169118,0.0108122,0.145325,0.144293
-308.029,0.961571,0.415398,2,7,0,312.919,0.0713912,-9.19954,-4.36136,-0.737221,-1.01167,0.51784,0.000101076,0.0126002,0.161806,0.133327
-307.614,0.405085,0.415398,2,3,0,312.133,-0.0789652,-7.59616,-3.77701,-0.323498,-1.30424,0.480269,0.000502124,0.0223788,0.209912,0.106726
-310.839,0.86931,0.415398,3,7,0,311.797,-0.0976133,-10.035,-3.67325,-1.09043,-0.641392,0.475616,4.38372e-05,0.0247648,0.125769,0.172466
-307.23,0.994565,0.415398,3,7,0,312.07,0.132927,-8.35218,-3.41779,-0.675067,-0.770866,0.533183,0.000235825,0.031744,0.168682,0.158146
-309.461,0.888784,0.415398,3,7,0,310.17,-0.471722,-5.43173,-2.7861,-0.489056,-1.31202,0.384209,0.00435646,0.0580802,0.190058,0.106075
-308.214,0.611879,0.415398,3,7,0,311.524,0.221327,-3.7507,-3.18137,-0.821112,-1.53613,0.555107,0.0229618,0.039873,0.152764,0.0885495
-308.547,0.69183,0.415398,2,7,0,312.636,0.548718,-10.925,-3.37933,-0.807524,-1.18896,0.633838,1.80019e-05,0.0329478,0.154209,0.116722
-309.543,0.838253,0.415398,3,7,0,310.296,0.376538,-11.0763,-4.51777,-0.619707,-1.02241,0.593038,1.54745e-05,0.0107955,0.174924,0.132279
-307.357,0.86212,0.415398,3,7,0,311.319,0.22932,-8.35019,-3.88046,-0.436547,-0.950084,0.55708,0.000236295,0.0202238,0.196282,0.139434
-306.444,0.881065,0.415398,2,3,0,309.518,0.178796,-6.91691,-3.37167,-0.802182,-1.21587,0.54458,0.000989911,0.0331928,0.154779,0.114332
-309.425,0.605518,0.415398,2,3,0,311.197,0.161845,-6.07119,-3.81898,-0.852551,-1.62445,0.540373,0.00230311,0.0214788,0.149449,0.0822959
-307.779,0.96988,0.415398,3,7,0,310.067,0.57499,-5.89041,-3.35686,-0.531893,-1.37942,0.639914,0.0027582,0.0336714,0.185038,0.100551
-306.509,0.946364,0.415398,3,7,0,308.084,0.208222,-4.85451,-3.39283,-0.736133,-1.33849,0.551868,0.00773292,0.0325204,0.161925,0.103879
-307.062,0.920692,0.415398,3,7,0,307.919,-0.0374483,-5.90321,-3.6102,-0.71785,-1.43011,0.490639,0.00272323,0.0263342,0.163933,0.0965404
-309.076,0.991244,0.415398,2,7,0,311.401,-0.118457,-7.66357,-4.69977,-0.652409,-0.691436,0.47042,0.000469409,0.00901537,0.171223,0.166857
-308.472,0.984271,0.415398,3,15,0,312.393,0.0487599,-6.11102,-3.95989,-1.05733,-0.821468,0.512188,0.00221338,0.0187086,0.12891,0.152726
-309.123,0.969341,0.415398,3,7,0,310.17,0.752301,-8.69223,-3.28989,-0.447297,-1.07717,0.67968,0.000167856,0.0359198,0.195002,0.127021
-309.41,0.423112,0.415398,3,15,0,311.77,0.320456,-10.5424,-4.16992,-0.449372,-0.749369,0.579435,2.63934e-05,0.0152183,0.194755,0.160479
-307.713,0.919193,0.415398,3,7,0,312.004,0.00125984,-9.46958,-3.34637,-0.430351,-0.946838,0.500315,7.71579e-05,0.0340142,0.197021,0.139761
-307.898,0.998057,0.415398,3,7,0,309.964,0.147988,-5.78985,-4.49374,-0.762642,-0.849399,0.53693,0.00304911,0.0110552,0.159037,0.149779
-307.626,0.971729,0.415398,3,7,0,308.695,0.310821,-9.36704,-4.09363,-0.659304,-0.984435,0.577086,8.54886e-05,0.016405,0.170448,0.136006
-312.522,0.923011,0.415398,3,7,0,313.045,0.376222,-9.16198,-2.44925,-0.94697,-0.874045,0.592962,0.000104944,0.0794932,0.139747,0.147207
-307.086,0.978156,0.415398,3,7,0,310.993,-0.0131013,-6.14485,-4.10019,-0.513464,-1.26664,0.496725,0.0021399,0.0162995,0.187191,0.109916
-309.377,0.945768,0.415398,3,7,0,310.673,0.121724,-10.2118,-4.40733,-0.354396,-1.26337,0.530394,3.67339e-05,0.012041,0.206158,0.110197
-307.767,1,0.415398,3,7,0,310.187,0.268821,-8.68254,-4.16942,-0.807225,-1.04476,0.566803,0.000169492,0.0152258,0.154241,0.130117
-307.507,0.978419,0.415398,3,7,0,310.243,0.0596401,-8.72065,-3.09735,-0.453049,-1.26758,0.514906,0.000163154,0.0432165,0.194318,0.109836
-309.243,0.00129688,0.415398,2,3,0,313.074,0.165151,-4.47223,-3.5854,-0.158124,-1.11298,0.541194,0.0112928,0.0269777,0.230276,0.123658
-310.059,0.977266,0.415398,3,7,0,310.823,0.236221,-5.30173,-3.48631,-0.126028,-0.838459,0.558782,0.00495828,0.0297042,0.234267,0.15093
-307.582,0.998322,0.415398,3,7,0,309.476,-0.154913,-5.59615,-3.99415,-0.335859,-1.29719,0.461349,0.00369839,0.0180898,0.208408,0.107319
-306.437,0.979312,0.415398,3,7,0,306.962,0.190824,-7.82505,-3.62228,-0.536442,-1.03598,0.547562,0.000399439,0.0260261,0.184508,0.130964
-306.988,0.989154,0.415398,3,7,0,308.48,0.43013,-7.45745,-3.15455,-0.648288,-0.943684,0.605905,0.000576791,0.0409122,0.171688,0.140078
-309.682,0.99059,0.415398,3,7,0,311.557,0.357847,-8.51361,-3.57834,-1.15412,-1.20372,0.588519,0.000200678,0.0271636,0.119868,0.115407
-307.688,0.989093,0.415398,3,7,0,310.507,0.460183,-7.62654,-3.593,-0.414754,-1.25095,0.613058,0.000487107,0.0267787,0.198886,0.111268
-307.277,0.970471,0.415398,3,7,0,308.231,0.316994,-8.49008,-3.77214,-0.769659,-1.22616,0.578592,0.000205455,0.0224856,0.158276,0.113427
-310.322,0.884011,0.415398,3,15,0,311.671,0.221309,-4.21356,-2.70364,-1.08114,-1.55471,0.555103,0.0145779,0.0627587,0.126645,0.0872037
-309.763,1,0.415398,2,3,0,310.783,0.257967,-3.81409,-2.65625,-0.985658,-1.51761,0.564137,0.0215817,0.0656047,0.135885,0.0899066
-308.023,0.993698,0.415398,3,7,0,308.579,-0.328645,-3.92526,-2.84789,-0.598393,-1.39775,0.41857,0.019355,0.0547906,0.177356,0.0990863
-306.412,0.72042,0.415398,3,7,0,309.911,-0.0909822,-6.66252,-3.28606,-0.655656,-1.17309,0.47727,0.0012763,0.0360526,0.170858,0.118149
-307.628,0.932243,0.415398,3,7,0,311.225,0.0139482,-5.56268,-3.73778,-0.449774,-0.749993,0.503487,0.0038238,0.0232533,0.194707,0.160411
-306.074,1,0.415398,3,7,0,309.146,0.174978,-5.61074,-3.30216,-0.549884,-1.11515,0.543633,0.00364503,0.0354971,0.182946,0.123456
-308.47,0.96092,0.415398,2,7,0,308.947,0.497075,-6.77274,-3.5358,-0.296193,-0.962145,0.621772,0.00114325,0.0283105,0.213244,0.138224
-307.385,0.999747,0.415398,3,15,0,308.659,0.33902,-4.42833,-2.86129,-0.703162,-1.23845,0.583952,0.0117936,0.0541006,0.165556,0.112353
-306.509,0.973678,0.415398,3,7,0,309.117,0.266335,-5.08936,-3.52554,-0.853214,-1.09061,0.566193,0.00612423,0.0285941,0.14938,0.125752
-306.798,0.981732,0.415398,3,7,0,307.248,0.0645394,-6.41035,-3.58706,-0.356243,-1.14778,0.516129,0.00164175,0.0269339,0.205935,0.120447
-307.806,0.887722,0.415398,3,7,0,311.432,0.163918,-8.48539,-3.81964,-0.965247,-1.08962,0.540888,0.00020642,0.0214648,0.137914,0.125845
-306.87,0.931953,0.415398,3,7,0,311.558,-0.219977,-5.86996,-3.19054,-0.6868,-1.21059,0.445226,0.00281504,0.0395233,0.167373,0.114798
-309.303,0.814074,0.415398,3,7,0,310.893,0.459229,-11.5046,-3.98299,-0.890112,-1.059,0.612831,1.00831e-05,0.0182892,0.145543,0.12875
-309.416,0.972618,0.415398,3,7,0,309.987,0.488149,-9.33845,-3.69894,-0.868558,-1.42918,0.61967,8.79682e-05,0.0241519,0.147777,0.0966133
-306.964,0.998488,0.415398,3,7,0,307.99,-0.0455867,-5.66237,-3.47406,-0.428297,-0.912788,0.488605,0.00346223,0.0300595,0.197267,0.143215
-307.176,0.996041,0.415398,3,15,0,307.696,-0.235594,-4.84627,-3.49032,-0.693132,-1.4407,0.441373,0.00779641,0.029589,0.166668,0.0957184
-307.807,0.986414,0.415398,3,7,0,309.673,-0.00633191,-3.72793,-2.96478,-0.856211,-1.2303,0.498417,0.023478,0.0490428,0.149066,0.113065
-307.172,0.977282,0.415398,3,7,0,308.658,0.0277638,-6.59744,-3.59511,-0.328896,-0.999872,0.506941,0.001362,0.0267238,0.209255,0.134483
-310.175,0.910112,0.415398,2,3,0,310.557,0.17883,-3.25154,-3.39355,-1.00398,-1.18249,0.544589,0.0372715,0.0324977,0.13408,0.117303
-309.034,0.973448,0.415398,3,7,0,310.454,0.14435,-8.3447,-3.24082,-0.871129,-0.598906,0.536025,0.000237597,0.0376583,0.14751,0.177297
-307.391,0.999173,0.415398,3,7,0,308.226,0.0446289,-7.21637,-3.13127,-0.600222,-0.812893,0.511155,0.000733922,0.0418355,0.177147,0.153637
-306.343,0.584835,0.415398,3,7,0,310.195,-0.0647539,-5.59037,-3.42266,-0.735906,-1.25815,0.483817,0.00371974,0.0315949,0.16195,0.110646
-307.3,0.97609,0.415398,3,7,0,307.768,0.158014,-3.96427,-3.34033,-0.841391,-1.26652,0.539422,0.0186283,0.0342134,0.150621,0.109927
-307.098,0.963974,0.415398,3,7,0,308.476,0.439214,-4.83955,-3.1836,-0.86532,-1.12144,0.608072,0.00784851,0.0397878,0.148114,0.122872
-307.87,0.581792,0.415398,2,7,0,310.99,-0.147998,-9.06499,-3.99178,-0.79945,-1.06571,0.463068,0.000115631,0.018132,0.155072,0.12811
-306.473,0.859042,0.415398,2,7,0,311.642,-0.0164266,-6.50258,-3.50263,-0.645219,-0.873183,0.495893,0.00149731,0.0292374,0.172034,0.147296
-307.798,0.957565,0.415398,3,7,0,309.137,0.245648,-8.2224,-3.07092,-0.728397,-1.42728,0.561105,0.000268496,0.0443228,0.162773,0.0967612
-309.982,0.89138,0.415398,2,3,0,310.732,0.15907,-7.98462,-2.68739,-0.865155,-1.45419,0.539684,0.000340546,0.0637214,0.148132,0.094679
-308.516,1,0.415398,3,7,0,309.442,-0.284933,-7.91273,-2.96871,-0.478723,-1.1313,0.429245,0.00036592,0.0488596,0.191277,0.12196
-309.205,0.81573,0.415398,3,7,0,312.57,-0.0119413,-6.60533,-3.12133,-0.53977,-1.77539,0.497015,0.00135131,0.042236,0.18412,0.072437
-308.219,0.999192,0.415398,3,7,0,311.369,-0.0323379,-6.67609,-3.29041,-0.919555,-1.44144,0.491916,0.00125911,0.0359018,0.142524,0.0956613
-307.256,0.916211,0.415398,3,7,0,309.007,0.448726,-8.38109,-3.78693,-0.765718,-0.947905,0.610336,0.000229108,0.0221627,0.158703,0.139653
-307.143,0.970825,0.415398,3,15,0,308.761,0.520674,-6.31432,-3.06714,-0.747071,-1.00868,0.627305,0.00180693,0.0444833,0.16073,0.133619
-309.352,0.77067,0.415398,2,7,0,310.803,0.296588,-12.9033,-3.06226,-0.459426,-1.14708,0.573608,2.48977e-06,0.0446912,0.193561,0.120511
-309.152,0.982387,0.415398,3,7,0,310.404,0.552719,-10.9753,-3.46808,-0.878023,-1.2647,0.634766,1.71183e-05,0.0302342,0.146794,0.110083
-309.626,0.348185,0.415398,3,7,0,312.079,-0.0631481,-11.9269,-3.40527,-0.980049,-1.19888,0.484218,6.60989e-06,0.0321311,0.136441,0.115837
-312.745,0.948114,0.415398,3,7,0,313.422,0.468957,-15.899,-3.99716,-0.489848,-0.669596,0.615137,1.24491e-07,0.0180365,0.189965,0.169294
-308.533,1,0.415398,2,3,0,309.556,0.509237,-6.2824,-3.10747,-0.91983,-1.41774,0.624627,0.00186542,0.0428003,0.142496,0.0975084
-308.918,0.909428,0.415398,3,7,0,311.205,0.452633,-10.9984,-4.07499,-0.522193,-0.977753,0.611265,1.67274e-05,0.0167085,0.18617,0.136669
-307.355,0.997054,0.415398,3,7,0,309.004,0.331854,-9.09372,-3.80037,-0.599371,-0.871577,0.58221,0.000112357,0.0218733,0.177244,0.147463
-307.384,0.986295,0.415398,3,7,0,310.475,0.304142,-7.11821,-3.70855,-0.527958,-1.40485,0.575455,0.000809558,0.0239265,0.185497,0.0985235
-309.03,0.92008,0.415398,2,7,0,310.329,-0.200122,-5.06914,-3.21662,-0.850359,-0.667241,0.450136,0.00624856,0.0385451,0.149679,0.169557
-307.795,0.953281,0.415398,3,7,0,308.125,0.289544,-4.56387,-3.17592,-0.828671,-1.54311,0.571885,0.0103141,0.0400822,0.151963,0.088042
-306.565,0.984046,0.415398,3,7,0,308.19,0.435764,-6.371,-3.49247,-0.553084,-1.10562,0.607249,0.00170752,0.0295271,0.182575,0.124344
-306.263,0.993477,0.415398,3,7,0,307.447,-0.0638369,-6.04157,-3.62926,-0.745979,-1.07416,0.484046,0.00237218,0.02585,0.160849,0.127307
-309.672,0.853692,0.415398,3,7,0,312.085,0.620875,-7.49515,-3.54761,-0.96409,-1.41928,0.650418,0.000555463,0.0279876,0.13803,0.0973876
-312.177,1,0.415398,2,3,0,312.809,-0.675289,-6.49779,-4.00127,-0.11116,-0.84731,0.337314,0.00150449,0.0179637,0.236119,0.149999
-308.002,0.986851,0.415398,3,7,0,308.77,0.008496,-7.17179,-2.95162,-0.397327,-1.00241,0.502124,0.000767355,0.0496599,0.200977,0.134234
-306.801,0.986129,0.415398,3,7,0,308.488,-0.123275,-4.65195,-3.30787,-0.841075,-1.17435,0.46922,0.00945272,0.0353022,0.150654,0.118035
-313.221,0.178368,0.415398,2,3,0,314.529,0.141939,-2.85591,-3.1913,-0.6936,-2.03188,0.535425,0.0543767,0.0394943,0.166616,0.0579482
-311.598,0.898387,0.415398,3,7,0,314.625,0.416901,-7.26322,-3.37555,-0.34715,-1.90442,0.602741,0.00070036,0.0330682,0.207037,0.0648044
-307.96,1,0.415398,3,7,0,314.378,0.521622,-6.91693,-3.35683,-0.677045,-1.45783,0.627527,0.000989889,0.0336722,0.168461,0.0943996
-309.074,0.953313,0.415398,3,7,0,310.419,0.599247,-6.50273,-3.41542,-0.325283,-1.40787,0.645484,0.00149709,0.0318171,0.209694,0.0982853
-307.433,1,0.415398,3,7,0,310.875,0.384711,-10.1507,-3.65545,-0.628061,-1.04051,0.595009,3.90457e-05,0.0251986,0.173975,0.130526
-308.91,0.901466,0.415398,2,3,0,310.74,0.43963,-5.12042,-2.97829,-0.314319,-0.98597,0.608171,0.00593802,0.0484161,0.21103,0.135854
-308.25,0.8386,0.415398,3,7,0,310.57,0.381819,-7.96102,-3.03585,-0.881673,-1.35648,0.594312,0.000348676,0.0458321,0.146416,0.102407
-307.906,0.985071,0.415398,3,7,0,310.27,-0.254639,-6.01494,-3.20742,-0.303752,-1.3226,0.436682,0.00243604,0.0388876,0.21232,0.105193
-307.401,0.996952,0.415398,3,7,0,311.039,-0.376467,-5.78982,-3.73059,-0.492247,-1.06275,0.406979,0.0030492,0.0234172,0.189682,0.128392
-309.659,0.878058,0.415398,3,7,0,311.932,-0.220844,-5.92605,-4.00781,-0.98306,-0.637488,0.445012,0.0026619,0.0178488,0.136143,0.172907
-309.289,0.867384,0.415398,3,7,0,311.919,0.482972,-3.67511,-3.37551,-0.710918,-1.47085,0.61845,0.02472,0.0330696,0.164698,0.0934068
-307.224,0.990727,0.415398,3,7,0,309.384,0.168646,-8.8573,-3.5845,-0.736495,-1.31146,0.542062,0.000142319,0.0270012,0.161886,0.106122
-307.301,0.998092,0.415398,3,7,0,308.122,-0.0491578,-9.73609,-3.38643,-0.682342,-1.21423,0.487713,5.91075e-05,0.0327224,0.167869,0.114477
-307.753,1,0.415398,3,7,0,309.036,-0.0124565,-9.32405,-3.03384,-0.549469,-1.26483,0.496886,8.92439e-05,0.0459203,0.182994,0.110072
-311.847,0.992179,0.415398,3,7,0,313.13,-0.182396,-14.5054,-3.99791,-0.717492,-1.46893,0.454527,5.01627e-07,0.0180231,0.163973,0.0935527
-306.487,0.877121,0.415398,3,7,0,309.153,0.133412,-4.59411,-3.651,-0.734334,-1.12019,0.533304,0.01001,0.025308,0.162122,0.122988
-307.189,0.994384,0.415398,3,7,0,308.041,0.379326,-4.62643,-2.99276,-0.674304,-1.03283,0.59371,0.00969472,0.047754,0.168767,0.131268
-307.327,0.991067,0.415398,3,7,0,309.684,-0.00158556,-5.14752,-3.99728,-0.411867,-0.951163,0.499604,0.00578019,0.0180343,0.199232,0.139325
-306.817,0.76073,0.415398,2,7,0,309.77,0.232799,-7.23326,-3.37819,-0.888912,-1.17206,0.557938,0.000721641,0.032984,0.145667,0.118242
-308.512,0.961042,0.415398,3,7,0,310.41,-0.0503601,-8.80536,-3.24236,-0.972522,-0.863136,0.487413,0.000149905,0.0376023,0.137189,0.148342
-309.569,0.980623,0.415398,3,7,0,311.922,-0.656781,-6.04723,-3.24915,-0.44912,-1.34218,0.341463,0.00235884,0.0373573,0.194785,0.103576
-307.286,0.997103,0.415398,3,15,0,313.013,0.264826,-6.34872,-3.6828,-0.900425,-0.768999,0.565822,0.00174593,0.0245354,0.144482,0.158348
-306.671,0.998225,0.415398,4,15,0,308.233,0.391959,-6.01913,-3.06448,-0.643284,-1.19813,0.596754,0.00242588,0.0445964,0.172252,0.115904
-307.213,1,0.415398,3,7,0,308.765,0.410734,-7.69857,-3.2821,-0.490393,-1.27947,0.601264,0.00045327,0.0361906,0.1899,0.10882
-306.958,0.999519,0.415398,3,7,0,307.567,0.329611,-6.00135,-4.00841,-0.798497,-0.997927,0.581665,0.0024693,0.0178383,0.155174,0.134675
-307.079,0.982063,0.415398,3,7,0,309.316,-0.219197,-4.8507,-3.84892,-0.747154,-1.12845,0.445419,0.00776215,0.0208585,0.160721,0.122223
-307.658,0.922696,0.415398,3,7,0,309.29,0.0129477,-5.39821,-4.37081,-0.598514,-0.829887,0.503237,0.00450429,0.0124832,0.177342,0.151834
-306.538,0.996931,0.415398,3,7,0,307.384,0.376718,-7.29978,-3.62208,-0.598369,-1.13131,0.593081,0.000675229,0.0260312,0.177358,0.12196
-307.664,0.95653,0.415398,3,7,0,308.918,0.0834326,-7.68222,-4.41804,-0.587562,-0.877211,0.520846,0.000460739,0.0119141,0.178597,0.146878

In [25]:
model.fits_.get('0').csv_files

AttributeError: Unknown variable name: csv_files
Available variables are logit_pi_know_group, logit_learn_group, logit_forget_group, logit_guess_group, logit_slip_group, pi_know, learn, forget, guess, slip

In [ ]:
model.fits_.get('0').

In [9]:
# 4) Predict hidden states
hidden_state_df = model.predict_posterior(data_df)
hidden_state_df

18:36:40 - cmdstanpy - INFO - Chain [1] start processing
18:36:40 - cmdstanpy - INFO - Chain [2] start processing
18:36:40 - cmdstanpy - INFO - Chain [3] start processing
18:36:40 - cmdstanpy - INFO - Chain [4] start processing
18:36:40 - cmdstanpy - INFO - Chain [2] done processing
18:36:40 - cmdstanpy - INFO - Chain [4] done processing
18:36:40 - cmdstanpy - INFO - Chain [1] done processing
18:36:40 - cmdstanpy - INFO - Chain [3] done processing
18:36:41 - cmdstanpy - WARNING - Sample doesn't contain draws from warmup iterations, rerun sampler with "save_warmup=True".
18:36:41 - cmdstanpy - INFO - Chain [1] start processing
18:36:41 - cmdstanpy - INFO - Chain [2] start processing
18:36:41 - cmdstanpy - INFO - Chain [3] start processing
18:36:41 - cmdstanpy - INFO - Chain [4] start processing
18:36:41 - cmdstanpy - INFO - Chain [1] done processing
18:36:41 - cmdstanpy - INFO - Chain [2] done processing
18:36:41 - cmdstanpy - INFO - Chain [3] done processing
18:36:41 - cmdstanpy - INFO - Chain [4] done processing
18:36:41 - cmdstanpy - WARNING - Sample doesn't contain draws from warmup iterations, rerun sampler with "save_warmup=True".
18:36:41 - cmdstanpy - INFO - Chain [1] start processing
18:36:41 - cmdstanpy - INFO - Chain [2] start processing
18:36:41 - cmdstanpy - INFO - Chain [3] start processing
18:36:41 - cmdstanpy - INFO - Chain [4] start processing
18:36:41 - cmdstanpy - INFO - Chain [3] done processing
18:36:41 - cmdstanpy - INFO - Chain [1] done processing
18:36:41 - cmdstanpy - INFO - Chain [4] done processing
18:36:41 - cmdstanpy - INFO - Chain [2] done processing
18:36:41 - cmdstanpy - WARNING - Sample doesn't contain draws from warmup iterations, rerun sampler with "save_warmup=True".

,variable,mean,std,median,2.5%,97.5%,ColumnNames.KC_ID
0,"pKnow[1,1]",0.525289,0.077541,0.527645,0.372113,0.674997,0
1,"pCorrectness[1,1]",0.543541,0.054127,0.543716,0.435433,0.647261,0
2,"pKnow[1,2]",0.145790,0.046478,0.141303,0.072718,0.252847,0
3,"pCorrectness[1,2]",0.276941,0.035450,0.275181,0.211371,0.350209,0
4,"pKnow[1,3]",0.029013,0.013508,0.026696,0.009955,0.062232,0
...,...,...,...,...,...,...,...
2995,"pCorrectness[50,5]",0.231637,0.038487,0.228289,0.162434,0.314082,1
2996,"pKnow[50,6]",0.015392,0.017706,0.009609,0.000643,0.060812,1
2997,"pCorrectness[50,6]",0.214515,0.042134,0.212272,0.136628,0.302180,1
2998,"pKnow[50,7]",0.010189,0.014853,0.004638,0.000153,0.051362,1
2999,"pCorrectness[50,7]",0.211115,0.043634,0.209491,0.129753,0.300458,1

In [10]:
# 5) Predict smoothed hidden states
smoothed_state_df = model.predict_smoothed_states_posterior(data_df)
smoothed_state_df

18:36:42 - cmdstanpy - INFO - Chain [1] start processing
18:36:42 - cmdstanpy - INFO - Chain [2] start processing
18:36:42 - cmdstanpy - INFO - Chain [3] start processing
18:36:42 - cmdstanpy - INFO - Chain [4] start processing
18:36:42 - cmdstanpy - INFO - Chain [1] done processing
18:36:42 - cmdstanpy - INFO - Chain [3] done processing
18:36:42 - cmdstanpy - INFO - Chain [4] done processing
18:36:42 - cmdstanpy - INFO - Chain [2] done processing
18:36:42 - cmdstanpy - WARNING - Sample doesn't contain draws from warmup iterations, rerun sampler with "save_warmup=True".
18:36:42 - cmdstanpy - INFO - Chain [1] start processing
18:36:42 - cmdstanpy - INFO - Chain [2] start processing
18:36:42 - cmdstanpy - INFO - Chain [3] start processing
18:36:42 - cmdstanpy - INFO - Chain [4] start processing
18:36:42 - cmdstanpy - INFO - Chain [1] done processing
18:36:42 - cmdstanpy - INFO - Chain [3] done processing
18:36:42 - cmdstanpy - INFO - Chain [2] done processing
18:36:42 - cmdstanpy - INFO - Chain [4] done processing
18:36:42 - cmdstanpy - WARNING - Sample doesn't contain draws from warmup iterations, rerun sampler with "save_warmup=True".
18:36:42 - cmdstanpy - INFO - Chain [1] start processing
18:36:42 - cmdstanpy - INFO - Chain [2] start processing
18:36:42 - cmdstanpy - INFO - Chain [3] start processing
18:36:42 - cmdstanpy - INFO - Chain [4] start processing
18:36:42 - cmdstanpy - INFO - Chain [4] done processing
18:36:42 - cmdstanpy - INFO - Chain [3] done processing
18:36:42 - cmdstanpy - INFO - Chain [1] done processing
18:36:42 - cmdstanpy - INFO - Chain [2] done processing
18:36:42 - cmdstanpy - WARNING - Sample doesn't contain draws from warmup iterations, rerun sampler with "save_warmup=True".

,variable,mean,std,median,2.5%,97.5%,ColumnNames.KC_ID
0,"know_probs[1,1]",0.009950,0.006642,0.008556,0.001478,0.026687,0
1,"know_probs[1,2]",0.005131,0.003698,0.004250,0.000686,0.014689,0
2,"know_probs[1,3]",0.005087,0.003758,0.004197,0.000651,0.015005,0
3,"know_probs[1,4]",0.000785,0.000651,0.000602,0.000082,0.002523,0
4,"know_probs[1,5]",0.000141,0.000138,0.000098,0.000011,0.000514,0
...,...,...,...,...,...,...,...
1495,"know_probs[50,3]",0.004938,0.008211,0.002453,0.000037,0.024761,1
1496,"know_probs[50,4]",0.001063,0.001662,0.000542,0.000018,0.005498,1
1497,"know_probs[50,5]",0.000493,0.000833,0.000216,0.000008,0.002727,1
1498,"know_probs[50,6]",0.000568,0.000920,0.000263,0.000008,0.002914,1
1499,"know_probs[50,7]",0.001639,0.002509,0.000734,0.000016,0.008371,1

In [11]:
correctness[0]

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0])

In [12]:
hidden_state_df.loc[hidden_state_df['variable'].str.startswith('pKnow[1,'),'mean'].reset_index(drop=True)

0     0.525289
1     0.145790
2     0.029013
3     0.128348
4     0.025949
5     0.007587
6     0.004560
7     0.004054
8     0.003968
9     0.003952
10    0.003949
11    0.003949
12    0.570393
13    0.210962
14    0.523402
15    0.809726
16    0.938776
17    0.737385
18    0.908555
19    0.969587
20    0.987662
21    0.992735
22    0.956362
23    0.538887
24    0.812045
25    0.926728
26    0.961134
27    0.970531
28    0.973080
29    0.973784
Name: mean, dtype: float64

In [13]:
smoothed_state_df.loc[smoothed_state_df["variable"].str.startswith("know_probs[1,"), "mean"]

0       0.009950
1       0.005131
2       0.005087
3       0.000785
4       0.000141
5       0.000041
6       0.000024
7       0.000022
8       0.000023
9       0.000033
10      0.000099
11      0.000559
600     0.862694
601     0.957017
602     0.979210
603     0.984352
604     0.984673
605     0.993372
606     0.995463
607     0.995616
608     0.994139
609     0.987611
610     0.987750
1150    0.995981
1151    0.997493
1152    0.997470
1153    0.995984
1154    0.989719
1155    0.963798
1156    0.852494
Name: mean, dtype: float64

In [14]:
test_df = pd.DataFrame({
    "variable": ["pKnow[1,1,1]", "pKnow[1,2,1]", "pKnow[1,3,1]", "pKnow[2,1,1]", "pCorrectness[2,2,1]", "pKnow[2,3,1]"]
    })
test_df.set_index("variable", inplace=True)

In [15]:
variable_indices = test_df.index.to_series().str.rstrip("]").str.split("[\\[,\\]]", expand=True)
variable_indices

                                0  1  2  3
variable
pKnow[1,1,1]                pKnow  1  1  1
pKnow[1,2,1]                pKnow  1  2  1
pKnow[1,3,1]                pKnow  1  3  1
pKnow[2,1,1]                pKnow  2  1  1
pCorrectness[2,2,1]  pCorrectness  2  2  1
pKnow[2,3,1]                pKnow  2  3  1

In [16]:
variable_indices.rename(columns={0: "variable_name", 1: "i", 2: "j", 3: "k"}, inplace=True)

In [17]:
test_df.ins

AttributeError: 'DataFrame' object has no attribute 'ins'

In [ ]:
test_df.insert(variable_indices)

In [ ]:
test_df.